baseURL = "/"
languageCode = "nb-NO"
title = "Advokatifrmaet Juristhuset"

disableKinds = ["RSS"]
enableRobotsTXT = true
disableAliases = true

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[[menu.main]]
    name = "Spisskompetanse"
    identifier = "tjenster"
    url = "/tjenester/"
    weight = -1

    [[menu.main]]
        name = "Ta Kontakt"
        identifier = "kontakt"
        url = "/kontakt/"
        pre = "btn ml-md-3 btn-round"

[params]
  FooterText = "Advokatfirmaet Juristhuset AS - Org. Nr. 918 529 349"
  author = "Nikola Tesla"
